on:
  pull_request: 
    branches: ['main']
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
         node-version: 14
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Typecheck
        run: tsc
      - name: Test
        run: jest
